use num_enum::TryFromPrimitive;
use strum_macros::{EnumCount, EnumIter};

use super::Error;

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, TryFromPrimitive, EnumCount, EnumIter)]
pub enum Pattern {
    Base = 0,
    Border,
    Bricks,
    Circle,
    Creeper,
    Cross,
    CurlyBorder,
    DiagonalLeft,
    DiagonalUpRight,
    DiagonalUpLeft,
    DiagonalRight,
    Flower,
    Globe,
    Gradient,
    GradientUp,
    HalfHorizontal,
    HalfHorizontalBottom,
    HalfVertical,
    HalfVerticalRight,
    Mojang,
    Piglin,
    Rhombus,
    Skull,
    SmallStripes,
    SquareBottomLeft,
    SquareBottomRight,
    SquareTopLeft,
    SquareTopRight,
    StraightCross,
    StripeBottom,
    StripeCenter,
    StripeDownLeft,
    StripeDownRight,
    StripeLeft,
    StripeMiddle,
    StripeRight,
    StripeTop,
    TriangleBottom,
    TriangleTop,
    TrianglesBottom,
    TrianglesTop,
    Flow,
    Guster,
}

impl Pattern {
    /// Pattern index in the banner font's BCD encoding
    pub const fn bcd(self) -> u8 {
        match self as u8 {
            0 => 0,
            ord => {
                let i = ord - 1;
                ((i / 10) << 4) | (i % 10 + 1)
            }
        }
    }

    pub fn name(self) -> &'static str {
        use Pattern::*;
        match self {
            Base => "Base",
            Border => "Bordure",
            Bricks => "Field Masoned",
            Circle => "Roundel",
            Creeper => "Creeper Charge",
            Cross => "Saltire",
            CurlyBorder => "Bordure Indented",
            DiagonalLeft => "Per Bend Sinister",
            DiagonalUpRight => "Per Bend Sinister Inverted",
            DiagonalUpLeft => "Per Bend Inverted",
            DiagonalRight => "Per Bend",
            Flower => "Flower Charge",
            Globe => "Globe",
            Gradient => "Gradient",
            GradientUp => "Base Gradient",
            HalfHorizontal => "Per Fess",
            HalfHorizontalBottom => "Per Fess Inverted",
            HalfVertical => "Per Pale",
            HalfVerticalRight => "Per Pale Inverted",
            Mojang => "Thing",
            Piglin => "Snout",
            Rhombus => "Lozenge",
            Skull => "Skull Charge",
            SmallStripes => "Paly",
            SquareBottomLeft => "Base Dexter Canton",
            SquareBottomRight => "Base Sinister Canton",
            SquareTopLeft => "Chief Dexter Canton",
            SquareTopRight => "Chief Sinister Canton",
            StraightCross => "Cross",
            StripeBottom => "Base",
            StripeCenter => "Pale",
            StripeDownLeft => "Bend Sinister",
            StripeDownRight => "Bend",
            StripeLeft => "Pale Dexter",
            StripeMiddle => "Fess",
            StripeRight => "Pale Sinister",
            StripeTop => "Chief",
            TriangleBottom => "Chevron",
            TriangleTop => "Inverted Chevron",
            TrianglesBottom => "Base Indented",
            TrianglesTop => "Chief Indented",
            Flow => "Flow",
            Guster => "Guster",
        }
    }

    pub fn code(self) -> &'static str {
        use Pattern::*;
        match self {
            Base => "b",
            Border => "bo",
            Bricks => "bri",
            Circle => "mc",
            Creeper => "cre",
            Cross => "cr",
            CurlyBorder => "cbo",
            DiagonalLeft => "ld",
            DiagonalUpRight => "rud",
            DiagonalUpLeft => "lud",
            DiagonalRight => "rd",
            Flower => "flo",
            Globe => "glb",
            Gradient => "gra",
            GradientUp => "gru",
            HalfHorizontal => "hh",
            HalfHorizontalBottom => "hhb",
            HalfVertical => "vh",
            HalfVerticalRight => "vhr",
            Mojang => "moj",
            Piglin => "pig",
            Rhombus => "mr",
            Skull => "sku",
            SmallStripes => "ss",
            SquareBottomLeft => "bl",
            SquareBottomRight => "br",
            SquareTopLeft => "tl",
            SquareTopRight => "tr",
            StraightCross => "sc",
            StripeBottom => "bs",
            StripeCenter => "cs",
            StripeDownLeft => "dls",
            StripeDownRight => "drs",
            StripeLeft => "ls",
            StripeMiddle => "ms",
            StripeRight => "rs",
            StripeTop => "ts",
            TriangleBottom => "bt",
            TriangleTop => "tt",
            TrianglesBottom => "bts",
            TrianglesTop => "tts",
            Flow => "flw",
            Guster => "gus",
        }
    }

    pub fn try_from_code(code: &str) -> Result<Self, Error> {
        use Pattern::*;
        Ok(match code {
            "b" => Base,
            "bo" => Border,
            "bri" => Bricks,
            "mc" => Circle,
            "cre" => Creeper,
            "cr" => Cross,
            "cbo" => CurlyBorder,
            "ld" => DiagonalLeft,
            "rud" => DiagonalUpRight,
            "lud" => DiagonalUpLeft,
            "rd" => DiagonalRight,
            "flo" => Flower,
            "glb" => Globe,
            "gra" => Gradient,
            "gru" => GradientUp,
            "hh" => HalfHorizontal,
            "hhb" => HalfHorizontalBottom,
            "vh" => HalfVertical,
            "vhr" => HalfVerticalRight,
            "moj" => Mojang,
            "pig" => Piglin,
            "mr" => Rhombus,
            "sku" => Skull,
            "ss" => SmallStripes,
            "bl" => SquareBottomLeft,
            "br" => SquareBottomRight,
            "tl" => SquareTopLeft,
            "tr" => SquareTopRight,
            "sc" => StraightCross,
            "bs" => StripeBottom,
            "cs" => StripeCenter,
            "dls" => StripeDownLeft,
            "drs" => StripeDownRight,
            "ls" => StripeLeft,
            "ms" => StripeMiddle,
            "rs" => StripeRight,
            "ts" => StripeTop,
            "bt" => TriangleBottom,
            "tt" => TriangleTop,
            "bts" => TrianglesBottom,
            "tts" => TrianglesTop,
            "flw" => Flow,
            "gus" => Guster,
            _ => return Err(Error::InvalidPattern(code.to_owned())),
        })
    }
}
