[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]

[build]
rustflags = [
  "-Zlocation-detail=none"
]

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "immediate-abort"
strip = true
incremental = false
